language: r
sudo: false
cache: packages
r_github_packages:
- gaborcsardi/gh
r_packages:
- knitr
- drat
- covr
after_success:
- Rscript -e 'library("covr");codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  drat.sh
env:
  global:
  - secure: MFlTIu9JRwiYYc03wmNu2YiOoS7iDZRpxGXiJEIE/m1WBfP2DCrps+DJfEXefcqsQ67NEUPbbpI5sJi7nJQlCsOurlLy1zoLo5KCwt9GbPqvYAEa1ffn586Dw7vRPI6/DWnwfktabypX4lJiye+2gmv9/mSrJe+4319qsgWgkeoDhWFdhB5yUeTsGp/hLhpkr6l3U4lUJJ4wl+VMKVPivgJsHS5JvjpupplNzSnNlThUDGIb+eGIWCP/tI4C//AXFEjMjeCOnkuMp/2lDSCHQccrSlBY+H9j8CkEigqZppfZgnBGAvZX1a48TWwPEpYZDBVOoKhiCX8mFwos/zcEmJcICDWLDAbwTJtQfrnD37JkIAcniFDGFRC9EVDljzrQjz7ySf4zJBM0asBcnwxh3EmGzQln0csPYXGHPfpCbno3X4ZPjTXR7mQ1n+r4QDf4qwN8mp21d0oRv6CLoJN4D/vf7wOy+oZf+KLJGSjcZr0A+xSiu87DSAoALN0u+Hyi6YM/oRBz6jBnyzwVe+MlcovkFBmUc07VNpNTUYnl57mjeZaYl/izKdQuxJMU6ZunBMuPRaYX+OJAGU54UIz/qKJ1pqQxsGPVxYj84lgj+EhILaS9SuygsUW1jyilzVeJApMdTRBrccLOXpsrBaz2BfNkQHLPJHsrCBCO3jzf46E=
  - secure: Wvb/Vy3l2az6E9f2RHZ1VkeFryQm1I5z38+m1yDShLJ04DhTgNnd0DgY0c0g4HA8B7ThH1Z/hgCeqYQm3JyZP1Tr/R/pvWv2roHL2LDNoIyDTEzikN6GL80Jb9rMvEVHDladiAX26UUHe0cPA2mB8VIoDlVO6FxUfBAmgq8A8xS9tOAZIAZf4YABHccZPkiBjWaPiCI9kwNd/imnYJ2syA9LOIF1yHYKfkerB6Onab1362RE5mAwuoEYg3m//IfwkUhFt1Zxu3dLeLpRssADPu4QkbhCdQJeUHeMAdc9+pOszO33AGG4EuY+pMjbZDdbeUb4v8rIbRISKZJPx7SgdBHGlkiKvaBGG0eB8bdSuy+OV2aUOkIDlXSV6dtpZfHd+urEMrU7fl3PYD3VyQRJ6qlsL0bkCX5uBygWZQ3wV579xWtQz57x/mqBrSBGwyPsXIA2U0NtQRT8IdE+Izbwzi4Asmn3XqX8ibtIXOgOSBHUciLS4cUTSs/H7Ch11f06J7VPwBbb49JvhMnew8J5poL1h4XhN8JcMU3HFb31TmOtmPFbcwY8kTZubl76iCi/rwO4YpDE44CRIbW3aNR/SAnYrQJ6pQ0GszLfzwRXoeC/+ghuUpcuz2Uv9dse3Ktzb/EzK+xED3vQAIgtADqUXyJg87t/uwMLYjT4NIwa/5s=
